"""rename_schema_to_data_schema

Revision ID: b5b230a4af75
Revises: ae6e3cdc180e
Create Date: 2025-07-24 18:49:02.929865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b230a4af75'
down_revision = 'ae6e3cdc180e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename schema column to data_schema in datasets table
    op.alter_column('datasets', 'schema', new_column_name='data_schema')
    
    op.create_table('analytics_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('show_dataset_overview', sa.Boolean(), nullable=True),
    sa.Column('show_missing_analysis', sa.Boolean(), nullable=True),
    sa.Column('show_correlation_analysis', sa.Boolean(), nullable=True),
    sa.Column('show_statistical_summary', sa.Boolean(), nullable=True),
    sa.Column('show_model_recommendations', sa.Boolean(), nullable=True),
    sa.Column('show_preprocessing_recommendations', sa.Boolean(), nullable=True),
    sa.Column('show_ai_insights', sa.Boolean(), nullable=True),
    sa.Column('show_visualizations', sa.Boolean(), nullable=True),
    sa.Column('include_correlation_heatmap', sa.Boolean(), nullable=True),
    sa.Column('include_missing_values_chart', sa.Boolean(), nullable=True),
    sa.Column('include_distribution_plots', sa.Boolean(), nullable=True),
    sa.Column('include_outlier_detection', sa.Boolean(), nullable=True),
    sa.Column('max_correlation_pairs', sa.Integer(), nullable=True),
    sa.Column('max_model_recommendations', sa.Integer(), nullable=True),
    sa.Column('include_advanced_stats', sa.Boolean(), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_configurations_id'), 'analytics_configurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_configurations_id'), table_name='analytics_configurations')
    op.drop_table('analytics_configurations')
    
    # Rename data_schema back to schema
    op.alter_column('datasets', 'data_schema', new_column_name='schema')
    # ### end Alembic commands ### 